version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9-slim
    
    working_directory: ~/hate-speech-detection
    
    steps:
      - checkout
      
      - run:
          name: Install system dependencies
          command: |
            apt-get update
            apt-get install -y gcc g++
      
      - run:
          name: Install Python dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      
      - run:
          name: Install package
          command: |
            pip install -e .
      
      - run:
          name: Verify installation
          command: |
            python -c "import hate_speech; print('Package installed successfully')"

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
